### ISSUE TITLE
Формирование архитектуры проекта

### ISSUE THREAD

**Issue by Roseskk** [DevBuffProject/DevBuff-frontend-next#3]
Добавить архитектуру папок.

**Comment by BigTows** [comment]
Удалить стандартные файлы, подготовить сервисный слой

**Comment by BigTows** [comment]
При попытке вызова `next export`

```
info  - using build directory: /Users/bigtows/Downloads/DevBuff-frontend-next/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/Users/bigtows/Downloads/DevBuff-frontend-next/next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /Users/bigtows/Downloads/DevBuff-frontend-next/node_modules/next/dist/export/index.js:156:23
    at async Span.traceAsyncFn (/Users/bigtows/Downloads/DevBuff-frontend-next/node_modules/next/dist/trace/trace.js:79:20)

```
